kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://localhost:5000"]
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./mount/control-plane
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: ./mount/worker
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: ./mount/worker2
        containerPath: /data