def listdir(path):
    b = local('ls {}'.format(path), quiet=True)
    files = str(b).split('\n')
    return files

def helm_install(name, values_file=None, chart=None, repo_name=None, repo_url=None, labels=[], namespace='default', resource_deps = [], deps=[], on_exist='ignore', force_repo_update=False, args=""):
    """ 
    Install a Helm chart with the specified values file and name.
    """
    if (repo_url!=None) and (repo_name!=None):
        repos = local("helm repo list | grep {}".format(repo_name))
        if repo_name not in str(repos): 
          local('helm repo add {} {}'.format(repo_name, repo_url))
          local('helm repo update')
        elif force_repo_update:
          print("Force update helm repo {}".format(repo_name))
          local('helm repo update')
        else:
          print("Helm repo {} already exists".format(repo_name))

    def get_helm_deployment_status(name):
        """Check if a Helm release is installed."""
        
        status = local('helm status {} | grep STATUS'.format(name), quiet=True)
        return status.strip().split(': ')[1] if status else ""
            
    def helm_deployment_present(name):
        """Check if a Helm release is present."""
        
        status = local('if helm list | grep -q {}; then echo "present"; else echo "missing"; fi'.format(name))
        return str(status).strip()

    status = helm_deployment_present(name)
    print('Helm status for {}: {}'.format(name, status))
    if status == 'present':
        if on_exist == 'skip':
          print('Helm release {} already exists, skipping installation.'.format(name))
          return
        elif on_exist == 'recreate':
          local('helm uninstall {}'.format(name))
        elif on_exist == 'ignore':
          pass
        else:
          fail('Unknown on_exist option: {}'.format(on_exist))
          return
    chart = chart or '.'
    
    values_file_str = ""
    if values_file:
      deps = deps + [values_file]
      watch_file(values_file)
      values_file_str="--values {}".format(values_file)

    resource_name = 'helm_install_{}'.format(name)
    local_resource(
        resource_name,
        cmd='helm upgrade --install {} {} {} --namespace {} --wait --timeout 5m {}'.format(
            name, chart, values_file_str, namespace, args
        ),
        deps=deps,
        resource_deps=resource_deps,
        labels=labels
    )
    print("local_resource created: {}".format(resource_name))
    
    if chart != '.':
        watch_file(chart)
    return resource_name

def sts_yaml(name, image, ports=[], envs = {}, command=None, args=None, service_enabled=True, replicas=1):
    
    env_tpl = "env:{envs}"
    env_value_tpl= """\n            - name: {name}\n              value: {value}"""
    
    command_str = "command: [{}]".format(command) if command else ""
    args_str = "args: [{}]".format(args) if args else ""

    env_values_str = ""
    env_str = ""
    if envs.keys():
        env_vars_str = "\n".join([env_value_tpl.format(name=env, value=value) for env, value in envs.items()])
        env_str = env_tpl.format(envs=env_vars_str)
    
    # map ports
    

    container_ports_str = "\n".join(["            - containerPort: {port}".format(port=port.split(":")[1]) for port in ports])
    sts_ports_str = """ports:\n{}""".format(container_ports_str) if ports else ""

    svc_ports_str = "ports:\n{}".format("\n".join(["    - port: {port}\n      targetPort: {port}\n      name: {name}".format(port=port.split(":")[1], name=port.split(":")[0]) for port in ports])) if ports and service_enabled else ""



    service_str = """
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  type: ClusterIP
  selector:
    app: {name}
  {ports}
    """.format(name=name, ports=svc_ports_str) if service_enabled else ""
    return blob("""
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {image}
          {ports}
          {env}
          {command}
          {args}
{service}
    """.format(
        name=name,
        image=image,
        env=env_str,
        command=command_str,
        args=args_str,
        service=service_str,
        ports=sts_ports_str,
        replicas=str(replicas)

    ))



def update_tiltit_btn():
  